
spring :
  profiles: local
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: system
    password: root

spring.batch.job.names: ${job.name:NONE}
